name = "Hammer"
author = "WaffleIBOT"
version = "1.13.4+1.21.3.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a9c576fcb1a1cd2b2fe42e8e48d75251b9858ad8e60ba144ecbc6bb1b74ff9f"

[versions]
minecraft = "1.21.3"
neoforge = "21.3.58"

[options]
acceptable-game-versions = ["1.21.2"]
