hash-format = "sha256"

[[files]]
file = "config/connector.json"
hash = "f84a2235b1d6f0fb5b1b096e2d1bf07ace41bfbb08273867d76961667a3cd7b3"

[[files]]
file = "config/dynamic_fps.json"
hash = "62721e017d7bd5f257dd8d2eaac63335c30ac6e3ad07b7302b84d27448f2a823"

[[files]]
file = "config/enhanced_bes.properties"
hash = "219204a2efc6d53ad8b3116db7392e039ba8e0ed5f45bc18562c9697bdf8f5c9"

[[files]]
file = "config/entityculling.json"
hash = "f47bc240cb42ff2838ec9f833b25b142f5f85b29caf5958f04df637252013b09"

[[files]]
file = "config/ferritecore.mixin.properties"
hash = "2fee62477522b340fb814284e126749bd7858d2f7c17a2400d09644e5c4d725d"

[[files]]
file = "config/immediatelyfast.json"
hash = "79d5fe80745f3ccc150714c8578fff788d4478054c471ed0282dd2d8bb44c7ab"

[[files]]
file = "config/modernfix-mixins.properties"
hash = "01fccbbb144a4bd999c5127480e587e626cf6552ff390eeec85a7e68aaed1d9f"

[[files]]
file = "config/sodium-options.json"
hash = "7024ae4da9a2af7955ff6e5b33c496e6aadcc5f7f3d0a9192294697ae9eaff68"

[[files]]
file = "config/threadtweak.json"
hash = "2189dfffbad0aa5ba4e8323071082826573c70db8291f1ea2d2a3ec5c88e1a32"

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "79ab4fc83d9cd5db3c935a4374b0328d0b1eaa056c5315f93551e914ab4fdcae"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "60187311fc010bbf513ed8451ff6417f75b6d82f3fef7cbfb9cc296b098ed636"
metafile = true

[[files]]
file = "mods/connector-extras.pw.toml"
hash = "194bcdf95b2917afbc9a47677707c12cd137e58ae2010b6fbd7c80c76a7811d4"
metafile = true

[[files]]
file = "mods/connector.pw.toml"
hash = "1cd21a6750edbbefe44a6fed98b31a8f5cb932a256d084eca146cd4d5e8133cf"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "3c87dcb63fa21b492b8a3ff6d91985bbaab16ea0064330b7a95c7fcf4d0603a8"
metafile = true

[[files]]
file = "mods/enhancedblockentities-0.10.1+1.21.jar"
hash = "bb8500024f2fd5f6ab09b6c48661d80783eb25f9c8b41bade242f84e21432b75"

[[files]]
file = "mods/entityculling.pw.toml"
hash = "df0c6c30ca36fa26f0a331c2f22a879c9cea01277c1342ddec35703e0342193a"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "ac87d2fd4d3d151915deb9a04b2ae2803291bb35d0e8fc8d66916f1269fd972a"
metafile = true

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
hash = "290787930537788be8554cf33c4d8dd4f0a801f3cd098daa448136881e83431a"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "441a70e869dbbc80df894683b0c1f49f09dcdcf68b177945fc52aad8273c3f13"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "f64b3f7f3d22351ad6bedfba759b1a3dc70d8cbc314db73cb446131a8e7db4ee"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "cf8096980a817d325b860d3d7e341883888584a50f481c1687c0dcd31e4fe28d"
metafile = true

[[files]]
file = "mods/radium.pw.toml"
hash = "73c4ed7ce7a640a07dd1ac0ee85937cabbfb604cb3b87425d9d412d032955125"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "49a0fc939b3bb385dba799c1f4cd93797493923835e596895d50f51d56145ac9"
metafile = true

[[files]]
file = "mods/sodiumleafculling.pw.toml"
hash = "67f2760a251265ebe9edd39cf62804bb9316fa6ff91e48055782ce725d1df9c3"
metafile = true

[[files]]
file = "mods/threadtweak.pw.toml"
hash = "aa9b0a592e0c8cd791e1194455a8569667d5a3f1e8b52a60bef79052474a0db8"
metafile = true

[[files]]
file = "options.txt"
hash = "c42352cd185e0d32c6c42f337a0cae8ea758e3db96a3b7468f1cf7faf8dc3e44"
