hash-format = "sha256"

[[files]]
file = "config/connector.json"
hash = "f00ca60d0f6e201b8f0b6fb0c571b98538817d2ea1e341110c53571fa408c0f1"

[[files]]
file = "config/dynamic_fps.json"
hash = "62721e017d7bd5f257dd8d2eaac63335c30ac6e3ad07b7302b84d27448f2a823"

[[files]]
file = "config/enhanced_bes.properties"
hash = "219204a2efc6d53ad8b3116db7392e039ba8e0ed5f45bc18562c9697bdf8f5c9"

[[files]]
file = "config/entityculling.json"
hash = "f47bc240cb42ff2838ec9f833b25b142f5f85b29caf5958f04df637252013b09"

[[files]]
file = "config/ferritecore.mixin.properties"
hash = "2fee62477522b340fb814284e126749bd7858d2f7c17a2400d09644e5c4d725d"

[[files]]
file = "config/immediatelyfast.json"
hash = "79d5fe80745f3ccc150714c8578fff788d4478054c471ed0282dd2d8bb44c7ab"

[[files]]
file = "config/modernfix-mixins.properties"
hash = "01fccbbb144a4bd999c5127480e587e626cf6552ff390eeec85a7e68aaed1d9f"

[[files]]
file = "config/sodium-options.json"
hash = "e4ff11608f1a0042290f924d3b759b1d5405dd5c3f2e686ed66604690c95a794"

[[files]]
file = "config/threadtweak.json"
hash = "2189dfffbad0aa5ba4e8323071082826573c70db8291f1ea2d2a3ec5c88e1a32"

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "79ab4fc83d9cd5db3c935a4374b0328d0b1eaa056c5315f93551e914ab4fdcae"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "24a71d71c1e31373819bd5d8192981bc200c990a385f03e27f44d4cfcc671f24"
metafile = true

[[files]]
file = "mods/connector-extras.pw.toml"
hash = "194bcdf95b2917afbc9a47677707c12cd137e58ae2010b6fbd7c80c76a7811d4"
metafile = true

[[files]]
file = "mods/connector.pw.toml"
hash = "1cd21a6750edbbefe44a6fed98b31a8f5cb932a256d084eca146cd4d5e8133cf"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "7cde7e1722cdbc76a3cba83db9f63d4bfa6c7f00b55e9eec9ee9c2bc036e71a7"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "e6eff4533154c7715f8a1fbc8c8b9c940e63b5878f6ce39e7ffef050a8da202f"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
hash = "719e6809d2aee4ff92f65daad9ab14f84f6b414d118f15b8a5c0cfc4230fd8ac"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "df0c6c30ca36fa26f0a331c2f22a879c9cea01277c1342ddec35703e0342193a"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "ac87d2fd4d3d151915deb9a04b2ae2803291bb35d0e8fc8d66916f1269fd972a"
metafile = true

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
hash = "290787930537788be8554cf33c4d8dd4f0a801f3cd098daa448136881e83431a"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "441a70e869dbbc80df894683b0c1f49f09dcdcf68b177945fc52aad8273c3f13"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "f64b3f7f3d22351ad6bedfba759b1a3dc70d8cbc314db73cb446131a8e7db4ee"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "cf8096980a817d325b860d3d7e341883888584a50f481c1687c0dcd31e4fe28d"
metafile = true

[[files]]
file = "mods/radium.pw.toml"
hash = "73068d4542b7451709bbacb7099a803974ec55a116015fd0bafe82047eb92635"
metafile = true

[[files]]
file = "mods/threadtweak.pw.toml"
hash = "aa9b0a592e0c8cd791e1194455a8569667d5a3f1e8b52a60bef79052474a0db8"
metafile = true

[[files]]
file = "options.txt"
hash = "c42352cd185e0d32c6c42f337a0cae8ea758e3db96a3b7468f1cf7faf8dc3e44"
