hash-format = "sha256"

[[files]]
file = "config/dynamic_fps.json"
hash = "62721e017d7bd5f257dd8d2eaac63335c30ac6e3ad07b7302b84d27448f2a823"

[[files]]
file = "config/embeddium-options.json"
hash = "e4ff11608f1a0042290f924d3b759b1d5405dd5c3f2e686ed66604690c95a794"

[[files]]
file = "config/entityculling.json"
hash = "f47bc240cb42ff2838ec9f833b25b142f5f85b29caf5958f04df637252013b09"

[[files]]
file = "config/ferritecore.mixin.properties"
hash = "2fee62477522b340fb814284e126749bd7858d2f7c17a2400d09644e5c4d725d"

[[files]]
file = "config/modernfix-mixins.properties"
hash = "01fccbbb144a4bd999c5127480e587e626cf6552ff390eeec85a7e68aaed1d9f"

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "51ac678d3646bcb97e13935ae67d32abbd55def714030b3b3433aa15b4b2c8af"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "82c3d1c66c2913dc5f442a98005de0a81c3d318b12862b265b7dadb9f8b0f064"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "4377e31daac95d15565b45238372a82ca5ef15d961cbdb7b33b720d004fbf3bc"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
hash = "433fa0f8f86403197f4db0cdee322b15281b5ed554d6b258ea11bb0cf63c5655"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "f1e7f2c8501b0d3f2427b0e4bd3d1a68ea969b1570991dc8f33ce462e6fc372c"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "33d8aed3c75ac75e772f4433319373e993b4c0a6a3e9b0f2d1d296abdfc0358b"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "4fade08e42058e0b243604b7fbeb8a0b05d7dbdc5d8ee468c9851350659dd975"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "074914c7fbc1ec5491e664520621556b3a395847c2a89e5c2cc5e4c9675feb34"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "07ee310e2470ada2a8c4d6aca496e8868d44efefda28978af00a58cbce406ee1"
metafile = true

[[files]]
file = "mods/radium.pw.toml"
hash = "f3328c48a082142c5efcf6e13682072586ad4760218b8f777dc919545813ea4c"
metafile = true

[[files]]
file = "options.txt"
hash = "c42352cd185e0d32c6c42f337a0cae8ea758e3db96a3b7468f1cf7faf8dc3e44"
