hash-format = "sha256"

[[files]]
file = "config/dynamic_fps.json"
hash = "62721e017d7bd5f257dd8d2eaac63335c30ac6e3ad07b7302b84d27448f2a823"

[[files]]
file = "config/embeddium-options.json"
hash = "e4ff11608f1a0042290f924d3b759b1d5405dd5c3f2e686ed66604690c95a794"

[[files]]
file = "config/entityculling.json"
hash = "f47bc240cb42ff2838ec9f833b25b142f5f85b29caf5958f04df637252013b09"

[[files]]
file = "config/ferritecore.mixin.properties"
hash = "2fee62477522b340fb814284e126749bd7858d2f7c17a2400d09644e5c4d725d"

[[files]]
file = "config/modernfix-mixins.properties"
hash = "01fccbbb144a4bd999c5127480e587e626cf6552ff390eeec85a7e68aaed1d9f"

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "adad3aebbe2a22c49bc0ce53be66b437f1998354576bec24af568c6e8faa0f4c"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "018eecf427d7a7541eff0ee2befc89634a13e0e99ba605aabe1e7da8fcb01cad"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "477469c0b8730becbf04b10df4972baa20c8d394e744739d7231a009f5b6b952"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
hash = "d68286cbcd2032e741ed14e7268083adc44faf146aa50e71271ed5977352355d"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "31351ed2c591d3ffd4817bb310eff0c586fcf01e18060e5ed5f33b0fb27646e6"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "4c1b778a25aa7335ae85ea0fa26216f0c7cd1585a1340d33e0189fc9149b6d57"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "aaf3da4ae8cee976bd6be032f69e7c4941fcd66a1af7ca01dc57875195de09fc"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "7687abfba0a6bb45923f65a091a029f6e7cea7c46d07e9a130380a026ce57a1a"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "22e18a9063a76927748040a1e22ebc7d65712c6fbac47d0a4fc774a0ec5427f4"
metafile = true

[[files]]
file = "options.txt"
hash = "c42352cd185e0d32c6c42f337a0cae8ea758e3db96a3b7468f1cf7faf8dc3e44"
